# Generated by Django 3.1.2 on 2020-11-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carpool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivers',
            options={'managed': False, 'verbose_name': 'drivers', 'verbose_name_plural': 'drivers'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'managed': False, 'verbose_name': 'locations', 'verbose_name_plural': 'locations'},
        ),
        migrations.AlterModelOptions(
            name='requests',
            options={'managed': False, 'verbose_name': 'Requests', 'verbose_name_plural': 'Requests'},
        ),
        migrations.AlterModelOptions(
            name='riders',
            options={'managed': False, 'verbose_name': 'Riders', 'verbose_name_plural': 'Riders'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'managed': False, 'verbose_name': 'Time', 'verbose_name_plural': 'Time'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
    ]
