# Generated by Django 3.1.2 on 2020-11-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carpool', '0002_auto_20201104_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='driver',
        ),
        migrations.DeleteModel(
            name='Riders',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Drivers',
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
